# Generated by Django 4.0.3 on 2022-11-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cladexallied', '0002_alter_banktranfer_transfer_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktranfer',
            name='ref_no',
            field=models.CharField(default=718653, max_length=8, verbose_name='Reference no'),
        ),
        migrations.AddField(
            model_name='internationaltransaction',
            name='ref_no',
            field=models.CharField(default=290321, max_length=8, verbose_name='Reference no'),
        ),
        migrations.AddField(
            model_name='receivedfunds',
            name='ref_no',
            field=models.CharField(default=763872, max_length=8, verbose_name='Reference no'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='account_number',
            field=models.IntegerField(default=1708077677),
        ),
    ]
